language: java
jdk:
  - openjdk11

branches:
  only:
    - travis

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - gesic84@gmail.com
